import { Inter } from 'next/font/google';
import Navbar from '../components/navbar/navbar';
import '../styles/globals.css';
import type { Metadata } from 'next';

const INTER = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={INTER.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
